// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Saskia
{
    internal sealed partial class Vsix
    {
        public const string Id = "Saskia.a0c9b46f-a5a0-47cd-a317-eea05cbf07fa";
        public const string Name = "Saskia";
        public const string Description = @"Flowerpot à la Python.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Stanislav Ko";
        public const string Tags = "";
    }
}
